providers = ["python"]

[phases.setup]
nixPkgs = ["python312", "zlib", "libjpeg", "libpng", "gcc", "binutils"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[phases.install]
cmds = ["python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]


[start]
cmd = "./start.sh"
